### ISSUE TITLE
Plugin breaks when running semantic-release via GitHub action codfish/semantic-release-action

### ISSUE THREAD

**Issue by gnarea** [KengoTODA/gradle-semantic-release-plugin#192]
It works when I run `npx semantic-release` but fails when I use the [codfish/semantic-release-action](https://github.com/codfish/semantic-release-action) action instead:

```
[7:24:58 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.24
[7:24:59 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[7:24:59 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "gradle-semantic-release-plugin"
[7:24:59 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[7:24:59 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[7:24:59 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "gradle-semantic-release-plugin"
[7:24:59 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[7:24:59 PM] [semantic-release] › ✔  Loaded plugin "publish" from "gradle-semantic-release-plugin"
[7:24:59 PM] [semantic-release] › ✔  Run automated release from branch master
[7:25:01 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[7:25:01 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[7:25:01 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[7:25:01 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "gradle-semantic-release-plugin"
[7:25:01 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "gradle-semantic-release-plugin"
[7:25:01 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Unexpected error: Gradle failed with status code 1
    at ChildProcess.child.on (/github/workspace/node_modules/gradle-semantic-release-plugin/lib/gradle.js:95:28)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12) pluginName: 'gradle-semantic-release-plugin' }
##[error]AggregateError: 
    Error: Unexpected error: Gradle failed with status code 1
        at ChildProcess.child.on (/github/workspace/node_modules/gradle-semantic-release-plugin/lib/gradle.js:95:28)
```

I had a quick look at the source code but it wasn't immediately obvious to me why it fails.

See error: https://github.com/relaycorp/relaynet-jvm/runs/477029471

Workaround: https://github.com/relaycorp/relaynet-jvm/commit/469cb816521ee840e72a49d4bdf1f12fcc2f69e9

**Comment by Silthus** [comment]
For me I get the same error when running it with `yarn semantic-release`: 

```
2020-05-05T13:27:16.2489496Z yarn install v1.22.4
2020-05-05T13:27:16.3593950Z [1/5] Validating package.json...
2020-05-05T13:27:16.3752257Z [2/5] Resolving packages...
2020-05-05T13:27:16.8475171Z [3/5] Fetching packages...
2020-05-05T13:27:34.4107110Z [4/5] Linking dependencies...
2020-05-05T13:27:41.2279695Z [5/5] Building fresh packages...
2020-05-05T13:27:41.8214913Z success Saved lockfile.
2020-05-05T13:27:41.8373458Z Done in 25.59s.
2020-05-05T13:27:42.0820632Z yarn run v1.22.4
2020-05-05T13:27:42.1357922Z $ semantic-release
2020-05-05T13:27:42.5135071Z [1:27:42 PM] [semantic-release] â€º â„¹  Running semantic-release version 17.0.7
2020-05-05T13:27:42.8286516Z [1:27:42 PM] [semantic-release] â€º âœ”  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
2020-05-05T13:27:42.8288881Z [1:27:42 PM] [semantic-release] â€º âœ”  Loaded plugin "verifyConditions" from "@semantic-release/github"
2020-05-05T13:27:42.8291568Z [1:27:42 PM] [semantic-release] â€º âœ”  Loaded plugin "verifyConditions" from "gradle-semantic-release-plugin"
2020-05-05T13:27:42.8294964Z [1:27:42 PM] [semantic-release] â€º âœ”  Loaded plugin "verifyConditions" from "@semantic-release/git"
2020-05-05T13:27:42.8298043Z [1:27:42 PM] [semantic-release] â€º âœ”  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2020-05-05T13:27:42.8304639Z [1:27:42 PM] [semantic-release] â€º âœ”  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2020-05-05T13:27:42.8308780Z [1:27:42 PM] [semantic-release] â€º âœ”  Loaded plugin "prepare" from "@semantic-release/changelog"
2020-05-05T13:27:42.8310766Z [1:27:42 PM] [semantic-release] â€º âœ”  Loaded plugin "prepare" from "gradle-semantic-release-plugin"
2020-05-05T13:27:42.8312920Z [1:27:42 PM] [semantic-release] â€º âœ”  Loaded plugin "prepare" from "@semantic-release/git"
2020-05-05T13:27:42.8315510Z [1:27:42 PM] [semantic-release] â€º âœ”  Loaded plugin "publish" from "@semantic-release/github"
2020-05-05T13:27:42.8318286Z [1:27:42 PM] [semantic-release] â€º âœ”  Loaded plugin "publish" from "gradle-semantic-release-plugin"
2020-05-05T13:27:42.8322302Z [1:27:42 PM] [semantic-release] â€º âœ”  Loaded plugin "addChannel" from "@semantic-release/github"
2020-05-05T13:27:42.8324564Z [1:27:42 PM] [semantic-release] â€º âœ”  Loaded plugin "success" from "@semantic-release/github"
2020-05-05T13:27:42.8327061Z [1:27:42 PM] [semantic-release] â€º âœ”  Loaded plugin "fail" from "@semantic-release/github"
2020-05-05T13:27:43.8126254Z [1:27:43 PM] [semantic-release] â€º âœ”  Run automated release from branch master on repository https://x-access-token:[secure]@github.com/mcSilthus/spigot-plugin-template
2020-05-05T13:27:44.1695841Z [1:27:44 PM] [semantic-release] â€º âœ”  Allowed to push to the Git repository
2020-05-05T13:27:44.1701211Z [1:27:44 PM] [semantic-release] â€º â„¹  Start step "verifyConditions" of plugin "@semantic-release/changelog"
2020-05-05T13:27:44.1722328Z [1:27:44 PM] [semantic-release] â€º âœ”  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
2020-05-05T13:27:44.1723447Z [1:27:44 PM] [semantic-release] â€º â„¹  Start step "verifyConditions" of plugin "@semantic-release/github"
2020-05-05T13:27:44.1746741Z [1:27:44 PM] [semantic-release] [@semantic-release/github] â€º â„¹  Verify GitHub authentication
2020-05-05T13:27:44.1839707Z [1:27:44 PM] [semantic-release] â€º âœ”  Completed step "verifyConditions" of plugin "@semantic-release/github"
2020-05-05T13:27:44.1840830Z [1:27:44 PM] [semantic-release] â€º â„¹  Start step "verifyConditions" of plugin "gradle-semantic-release-plugin"
2020-05-05T13:27:45.4016083Z [1:27:45 PM] [semantic-release] â€º âœ–  Failed step "verifyConditions" of plugin "gradle-semantic-release-plugin"
2020-05-05T13:27:45.4021006Z [1:27:45 PM] [semantic-release] â€º â„¹  Start step "verifyConditions" of plugin "@semantic-release/git"
2020-05-05T13:27:45.4149423Z [1:27:45 PM] [semantic-release] â€º âœ”  Completed step "verifyConditions" of plugin "@semantic-release/git"
2020-05-05T13:27:45.4194403Z [1:27:45 PM] [semantic-release] â€º âœ–  An error occurred while running semantic-release: Error: Unexpected error: Gradle failed with status code 1
2020-05-05T13:27:45.4195603Z     at ChildProcess.<anonymous> (/home/runner/work/spigot-plugin-template/spigot-plugin-template/node_modules/gradle-semantic-release-plugin/lib/gradle.js:95:28)
2020-05-05T13:27:45.4196141Z     at ChildProcess.emit (events.js:315:20)
2020-05-05T13:27:45.4196562Z     at maybeClose (internal/child_process.js:1051:16)
2020-05-05T13:27:45.4197385Z     at Socket.<anonymous> (internal/child_process.js:442:11)
2020-05-05T13:27:45.4197817Z     at Socket.emit (events.js:315:20)
2020-05-05T13:27:45.4198222Z     at Pipe.<anonymous> (net.js:671:12) {
2020-05-05T13:27:45.4198900Z   pluginName: 'gradle-semantic-release-plugin'
2020-05-05T13:27:45.4199326Z }
2020-05-05T13:27:45.4212232Z AggregateError: 
2020-05-05T13:27:45.4212728Z     Error: Unexpected error: Gradle failed with status code 1
2020-05-05T13:27:45.4213877Z         at ChildProcess.<anonymous> (/home/runner/work/spigot-plugin-template/spigot-plugin-template/node_modules/gradle-semantic-release-plugin/lib/gradle.js:95:28)
2020-05-05T13:27:45.4214901Z     at /home/runner/work/spigot-plugin-template/spigot-plugin-template/node_modules/[4msemantic-release[24m/lib/plugins/pipeline.js:54:11
2020-05-05T13:27:45.4215735Z [90m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[39m
2020-05-05T13:27:45.4216742Z     at async Object.pluginsConf.<computed> [as verifyConditions] (/home/runner/work/spigot-plugin-template/spigot-plugin-template/node_modules/[4msemantic-release[24m/lib/plugins/index.js:80:11)
2020-05-05T13:27:45.4255703Z     at async run (/home/runner/work/spigot-plugin-template/spigot-plugin-template/node_modules/[4msemantic-release[24m/index.js:94:3)
2020-05-05T13:27:45.4256694Z     at async module.exports (/home/runner/work/spigot-plugin-template/spigot-plugin-template/node_modules/[4msemantic-release[24m/index.js:259:22)
2020-05-05T13:27:45.4468741Z     at async module.exports (/home/runner/work/spigot-plugin-template/spigot-plugin-template/node_modules/[4msemantic-release[24m/cli.js:55:5)error Command failed with exit code 1.
```

**Comment by Silthus** [comment]
Could this have to do with the node version? I am using node14 and maybe the Github action is too?

**Comment by Silthus** [comment]
I found the problem, for me at least: I had some variables in my gradle home properties that needed to be defined at build. I forgot that and throwed an error on startup.

Maybe a better error output of the underlying failing gradle task would be good?

**Comment by KengoTODA** [comment]
> Maybe a better error output of the underlying failing gradle task would be good?

Thanks @Silthus for your work regarding #412 and #430, now I think we can close this issue safely.
